source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
project 'DataSecurityWorkshop.xcodeproj'
inhibit_all_warnings!
use_frameworks!

target :"DataSecurityWorkshop" do

  pod 'themis', '0.10.4'
  pod 'Valet', '3.2.3'

end